### ISSUE TITLE
remove default secret key

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-django#10]
want to make sure in prod this won't run unless it's set to something unique

**Comment by josephabrahams** [comment]
Does https://github.com/istrategylabs/mo-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/app.json#L8 take care of this?

Still like the idea of people knowing what a secret key is. Thoughts?

**Comment by jcarbaugh** [comment]
That _app.json_ entry will only generate the secret key when using the Heroku deploy buttons. I wish cookiecutter provided a function to generate a random string like that, but it doesn't right now without writing custom post-gen hooks.

I'd be fine removing a default from _settings.py_ and put something in _env.example_ instead: https://github.com/istrategylabs/mo-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/env.example

 It needs to be set in the env file anyway so that should have at least a placeholder for it in there. Or maybe include a default SECRET_KEY only when DEBUG is True.

**Comment by jcarbaugh** [comment]
SECRET_KEY removed in 9623031a4a124bd2d8d0f5ac2772895f444de911
